### ISSUE TITLE
re-publish package

### ISSUE THREAD

**Issue by LarryBattle** [nguyenj/online-status-event#4]
NPM doesn't have your repo details committed here.
- npm package: https://www.npmjs.com/package/online-status-event
- Commit: https://github.com/nguyenj/online-status-event/commit/fa6222576ed9d31a515c3147f0ad9c0b9b8b1452#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34

Please re-publish latest master to npm.

**Comment by nguyenj** [comment]
@LarryBattle I apologize for the late response. I have bumped the package.
